config/routes.rb
Rails.application.routes.draw do
  root 'trades#index'
  resources :trades, only: [:index] do
    collection do
      get :binance_chart_data
      get :bitmex_chart_data
      post :export
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trade.rb
# == Schema Information
#
# Table name: trades
#
#  id         :bigint(8)        not null, primary key
#  price      :float
#  quantity   :float
#  taker_side :string
#  traded_at  :datetime
#  source     :string
#  flow       :float
#
# Indexes
#
#  index_trades_on_traded_at  (traded_at)
#

class Trade < ActiveRecord::Base
  InvalidGroupBy = Class.new(ArgumentError)

  CSV_COLUMNS = %w{ traded_at taker_side price quantity flow }

  SOURCES = [
    BINANCE  = :binance,
    BITMEX   = :bitmex,
    COIN_API = :coin_api,
  ].freeze

  TAKER_SIDES = [
    BUY = "BUY".freeze,
    SELL = "SELL".freeze,
  ].freeze

  VISUALIZATION_GROUP_BYS = [
    GROUP_BY_SECOND = :second,
    DEFAULT_VISUALIZATION_GROUP_BY = GROUP_BY_MINUTE = :minute,
    GROUP_BY_HOUR = :hour,
    DEFAULT_WINDOW_UNIT = GROUP_BY_DAY = :day,
  ].freeze

  MOVING_AVERAGE_NUMERATORS = [
    1,
    4,
    7,
    12,
    24,
    DEFAULT_MOVING_AVERAGE_NUMERATOR = 30,
  ].freeze

  MOVING_AVERAGE_DENOMINATORS = [
    1,
    5,
    10,
    DEFAULT_MOVING_AVERAGE_DENOMINATOR = 30,
    60,
    120,
  ].freeze

  DEFAULT_WINDOW_SIZE = 1

  before_validation :calculate_flow

  scope :binance, -> { where(source: BINANCE) }
  scope :bitmex, -> { where(source: BITMEX) }
  scope :coin_api, -> { where(source: COIN_API) }
  scope :buyer_side, -> { where(taker_side: BUY) }
  scope :seller_side, -> { where(taker_side: SELL) }
  scope :variable_group_by, -> (group_by, field, range) do
    case group_by
    when Trade::GROUP_BY_SECOND
      group_by_second(field, range: range)
    when Trade::GROUP_BY_MINUTE
      group_by_minute(field, range: range)
    when Trade::GROUP_BY_HOUR
      group_by_hour(field, range: range)
    when Trade::GROUP_BY_DAY
      group_by_day(field, range: range)
    else
      raise InvalidGroupBy
    end
  end

  private

  def calculate_flow
    if price.present? && quantity.present?
      self.flow = price * quantity
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  def index
    export_dates_hash = Trade.group_by_week(:traded_at).minimum(:traded_at).keys.each_with_object({}) do |first_of_week, result|
      result[first_of_week] = (first_of_week + 1.day).at_end_of_week
    end

    render template: 'trades/index', locals: { export_dates_hash: export_dates_hash }
  end

  def binance_chart_data
    starting_time = params.fetch(:start_date, Date.today).to_date.at_beginning_of_day
    ending_time = params.fetch(:end_date, Trade::DEFAULT_WINDOW_SIZE.days.from_now).to_date.at_end_of_day
    range = starting_time..ending_time
    group_by = params.fetch(:group_by, Trade::DEFAULT_VISUALIZATION_GROUP_BY).to_sym
    moving_average_numerator = params.fetch(:moving_average_numerator, Trade::DEFAULT_MOVING_AVERAGE_NUMERATOR).to_i
    moving_average_denominator = params.fetch(:moving_average_denominator, Trade::DEFAULT_MOVING_AVERAGE_DENOMINATOR).to_i

    base_query = Trade.binance.where(traded_at: range).variable_group_by(group_by, :traded_at, range)
    grouped_buys = base_query.buyer_side.sum(:flow)
    grouped_sells = base_query.seller_side.sum(:flow)
    grouped_prices = base_query.average(:price)

    overlapping_group_by_units = grouped_buys.keys & grouped_sells.keys

    result = overlapping_group_by_units.each_with_object({}).each_with_index do |(group_by_unit, result), i|
      result[:flow_difference] ||= {}
      result[:moving_average] ||= {}
      result[:average_price] ||= {}

      result[:flow_difference][group_by_unit] = grouped_buys[group_by_unit] - grouped_sells[group_by_unit]
      starting_index = i - (moving_average_numerator - 1)
      if starting_index >= 0
        group_by_units_to_average = overlapping_group_by_units[starting_index..i]
        result[:moving_average][group_by_unit] = result[:flow_difference].slice(*group_by_units_to_average).values.sum / moving_average_denominator
      end
    end

    result[:average_price] = grouped_prices

    render json: [
        { name: 'Flow (buys - sells)', data: result[:flow_difference] },
        { name: 'Moving Average', data: result[:moving_average] },
        { name: 'Price', data: result[:average_price] }
      ],
      status: :ok
  end

  def bitmex_chart_data
    starting_time = params.fetch(:start_date, Date.today).to_date.at_beginning_of_day
    ending_time = params.fetch(:end_date, Trade::DEFAULT_WINDOW_SIZE.days.from_now).to_date.at_end_of_day
    range = starting_time..ending_time
    group_by = params.fetch(:group_by, Trade::DEFAULT_VISUALIZATION_GROUP_BY).to_sym
    moving_average_numerator = params.fetch(:moving_average_numerator, Trade::DEFAULT_MOVING_AVERAGE_NUMERATOR).to_i
    moving_average_denominator = params.fetch(:moving_average_denominator, Trade::DEFAULT_MOVING_AVERAGE_DENOMINATOR).to_i

    base_query = Trade.bitmex.where(traded_at: range).variable_group_by(group_by, :traded_at, range)
    grouped_buys = base_query.buyer_side.sum(:flow)
    grouped_sells = base_query.seller_side.sum(:flow)
    grouped_prices = base_query.average(:price)

    overlapping_group_by_units = grouped_buys.keys & grouped_sells.keys

    result = overlapping_group_by_units.each_with_object({}).each_with_index do |(group_by_unit, result), i|
      result[:flow_difference] ||= {}
      result[:moving_average] ||= {}
      result[:average_price] ||= {}

      result[:flow_difference][group_by_unit] = grouped_buys[group_by_unit] - grouped_sells[group_by_unit]
      starting_index = i - (moving_average_numerator - 1)
      if starting_index >= 0
        group_by_units_to_average = overlapping_group_by_units[starting_index..i]
        result[:moving_average][group_by_unit] = result[:flow_difference].slice(*group_by_units_to_average).values.sum / moving_average_denominator
      end
    end

    result[:average_price] = grouped_prices

    render json: [
        { name: 'Flow (buys - sells)', data: result[:flow_difference] },
        { name: 'Moving Average', data: result[:moving_average] },
        { name: 'Price', data: result[:average_price] }
      ],
      status: :ok
  end

  def export
    respond_to do |format|
      format.csv do
        starting_time = params.fetch(:starting_time).to_datetime
        ending_time = params.fetch(:ending_time).to_datetime
        filename =
        trades = Trade.where(traded_at: starting_time..ending_time)

        send_data CsvGenerator.new(trades).generate, filename: "#{starting_time.strftime("%Y_%b%d")}_#{ending_time.strftime("%Y_%b%d")}.csv"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trade_helper.rb
module TradeHelper
  def export_button(starting_time:, ending_time:)
    stringified_time_range = "#{starting_time.strftime("%b%d")}_#{ending_time.strftime("%b%d")}"
    button_to "Export #{starting_time.strftime("%Y")} #{stringified_time_range} Trades", { controller: :trades, action: :export, starting_time: starting_time, ending_time: ending_time, format: :csv }, { id: "export_button_#{stringified_time_range}" }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trades/index.html.erb
<div>Binance</div>
<%= line_chart binance_chart_data_trades_url({ group_by: Trade::DEFAULT_VISUALIZATION_GROUP_BY }), points: false, refresh: 60 %>
<div>Bitmex</div>
<%= line_chart bitmex_chart_data_trades_url({ group_by: Trade::DEFAULT_VISUALIZATION_GROUP_BY }), points: false, refresh: 60 %>
<div>Configuration</div>
<table>
  <tr>
    <th>
      Group By
    </th>
    <td>
      <div>
        <% Trade::VISUALIZATION_GROUP_BYS.each do |group_by| %>
            <%= radio_button_tag(:group_by, group_by, group_by == Trade::DEFAULT_VISUALIZATION_GROUP_BY ? true : false) %>
            <%= label(:group_by, group_by) %>
        <% end %>
      </div>
    </td>
  </tr>
  <tr>
    <th>
      Moving Average Numerator
    </th>
    <td>
      <div>
        <% Trade::MOVING_AVERAGE_NUMERATORS.each do |moving_average_numerator| %>
            <%= radio_button_tag(:moving_average_numerator, moving_average_numerator, moving_average_numerator == Trade::DEFAULT_MOVING_AVERAGE_NUMERATOR ? true : false) %>
            <%= label(:moving_average_numerator, moving_average_numerator) %>
        <% end %>
      </div>
    </td>
  </tr>
  <tr>
    <th>
      Moving Average Denominator
    </th>
    <td>
      <div>
        <% Trade::MOVING_AVERAGE_DENOMINATORS.each do |moving_average_denominator| %>
            <%= radio_button_tag(:moving_average_denominator, moving_average_denominator, moving_average_denominator == Trade::DEFAULT_MOVING_AVERAGE_DENOMINATOR ? true : false) %>
            <%= label(:moving_average_denominator, moving_average_denominator) %>
        <% end %>
      </div>
    </td>
  </tr>
  <tr>
    <th>
      Window Start
    </th>
    <td>
      <div>
        <input class="datetimepicker" id="datepicker-start" value=<%= Date.today.at_beginning_of_day %>></input>
      </div>
    </td>
  </tr>
  <tr>
    <th>
      Window End
    </th>
    <td>
      <div>
        <input class="datetimepicker" id="datepicker-end" value=<%= Trade::DEFAULT_WINDOW_SIZE.days.from_now.at_end_of_day %>></input>
      </div>
    </td>
  </tr>
</table>
<%= button_tag 'Apply', { id: :apply_button } %>

<%# export_dates_hash.each do |starting_time, ending_time| %>
  <%# export_button(starting_time: starting_time, ending_time: ending_time) %>
<%# end %>